 var app = angular.module('myApp',[]);
         app.controller("myController",function($scope){
         
         // working with ng-options with Array data
         $scope.countries = [
         {"country_code":"Algeria","country_name":"Algeria"},
         {"country_code":"Andorra","country_name":"Andorra"},
         {"country_code":"Angola","country_name":"Angola"},
         {"country_code":"Anguilla","country_name":"Anguillaa"},
         {"country_code":"Antigua and Barbuda","country_name":"Antigua and Barbuda"},
         {"country_code":"Argentina","country_name":"Argentina"},
         {"country_code":"Armenia","country_name":"Armenia"},
         {"country_code":"Austria","country_name":"Austria"},
         {"country_code":"Azerbaijan","country_name":"Azerbaijan"},
         {"country_code":"Bahamas","country_name":"Bahamas"},
         {"country_code":"Bahrain","country_name":"Bahrain"},
         {"country_code":"Bangladesh","country_name":"Bangladesh"},
         {"country_code":"Barbados","country_name":"Barbados"},
         {"country_code":"Belarus","country_name":"Belarus"},
         {"country_code":"Belgium","country_name":"Belgium"},
         {"country_code":"Belize","country_name":"Belize"},
         {"country_code":"Bermuda","country_name":"Bermuda"},
         {"country_code":"Bhutan","country_name":"Bhutan"},
         {"country_code":"Bolivia","country_name":"Bolivia"},
         {"country_code":"Bosnia Herzegovina","country_name":"Bosnia Herzegovina"},
         {"country_code":"Botswana","country_name":"Botswana"},
         {"country_code":"Brazil","country_name":"Brazil"},
         {"country_code":"Brunei","country_name":"Brunei"},
         {"country_code":"Bulgaria","country_name":"Bulgaria"},
         {"country_code":"Burkina Faso","country_name":"Burkina Faso"},
         {"country_code":"Burundi","country_name":"Burundi"},
         {"country_code":"Cambodia","country_name":"Cambodia"},
         {"country_code":"Cameroon","country_name":"Cameroon"},
         {"country_code":"Canada","country_name":"Canada"},
         {"country_code":"Cape Verde","country_name":"Cape Verde"},
         {"country_code":"Cayman Islands","country_name":"Cayman Islands"},
         {"country_code":"Central African Republic","country_name":"Central African Republic"},
         {"country_code":"Chad","country_name":"Chad"},
         {"country_code":"Chile","country_name":"Chile"},
         {"country_code":"China","country_name":"China"},
         {"country_code":"Colombia","country_name":"Colombia"},
         {"country_code":"Comoros","country_name":"Comoros"},
         {"country_code":"Congo","country_name":"Congo"},
         {"country_code":"Congo (DRC)","country_name":"Congo (DRC)"},
         {"country_code":"Cook Islands","country_name":"Cook Islands"},
         {"country_code":"Costa Rica","country_name":"Costa Rica"},
         {"country_code":"Cote d'Invoire","country_name":"Cote d'Invoire"},
         {"country_code":"Croatia","country_name":"Croatia"},
         {"country_code":"Cuba","country_name":"Cuba"},
         {"country_code":"Cyprus","country_name":"Cyprus"},
         {"country_code":"Czech Republic","country_name":"Czech Republic"},
         {"country_code":"Denmark","country_name":"Denmark"},
         {"country_code":"Djibouti","country_name":"Djibouti"},
         {"country_code":"Dominica","country_name":"Dominica"},
         {"country_code":"Dominican Republic","country_name":"Dominican Republic"},
         {"country_code":"East Timor","country_name":"East Timor"},
         {"country_code":"Ecuador","country_name":"Ecuador"},
         {"country_code":"Egypt","country_name":"Egypt"},
         {"country_code":"El Salvador","country_name":"El Salvador"},
         {"country_code":"Equatorial Guinea","country_name":"Equatorial Guinea"},
         {"country_code":"Eritrea","country_name":"Eritrea"},
         {"country_code":"Estonia","country_name":"Estonia"},
         {"country_code":"Ethiopia","country_name":"Ethiopia"},
         {"country_code":"Falkland Islands","country_name":"Falkland Islands"},
         {"country_code":"Faroe Islands","country_name":"Faroe Islands"},
         {"country_code":"Fiji","country_name":"Fiji"},
         {"country_code":"Finland","country_name":"Finland"},
         {"country_code":"France","country_name":"France"},
         {"country_code":"French Guiana","country_name":"French Guiana"},
         {"country_code":"French Polynesia","country_name":"French Polynesia"},
         {"country_code":"Gabon","country_name":"Gabon"},
         {"country_code":"Gambia","country_name":"Gambia"},
         {"country_code":"Georgia","country_name":"Georgia"},
         {"country_code":"Germany","country_name":"Germany"},
         {"country_code":"Ghana","country_name":"Ghana"},
         {"country_code":"Gibraltar","country_name":"Gibraltar"},
         {"country_code":"Greece","country_name":"Greece"},
         {"country_code":"Greenland","country_name":"Greenland"},
         {"country_code":"Grenada","country_name":"Grenada"},
         {"country_code":"Guadeloupe","country_name":"Guadeloupe"},
         {"country_code":"Guam","country_name":"Guam"},
         {"country_code":"Guatemala","country_name":"Guatemala"},
         {"country_code":"Guinea","country_name":"Guinea"},
         {"country_code":"Guinea-Bissau","country_name":"Guinea-Bissau"},
         {"country_code":"Guyana","country_name":"Guyana"},
         {"country_code":"Haiti","country_name":"Haiti"},
         {"country_code":"Honduras","country_name":"Honduras"},
         {"country_code":"Hong Kong","country_name":"Hong Kong"},
         {"country_code":"Hungary","country_name":"Hungary"},
         {"country_code":"Iceland","country_name":"Iceland"},
         {"country_code":"India","country_name":"India"},
         {"country_code":"Indonesia","country_name":"Indonesia"},
         {"country_code":"Iran","country_name":"Iran"},
         {"country_code":"Iraq","country_name":"Iraq"},
         {"country_code":"Ireland","country_name":"Ireland"},
         {"country_code":"Israel","country_name":"Israel"},
         {"country_code":"Italy","country_name":"Italy"},
         {"country_code":"Jamaica","country_name":"Jamaica"},
         {"country_code":"Japan","country_name":"Japan"},
         {"country_code":"Jordan","country_name":"Jordan"},
         {"country_code":"Kazakhstan","country_name":"Kazakhstan"},
         {"country_code":"Kenya","country_name":"Kenya"},
         {"country_code":"Kiribati","country_name":"Kiribati"},
         {"country_code":"South Korea","country_name":"South Korea"},
         {"country_code":"Kuwait","country_name":"Kuwait"},
         {"country_code":"Kyrgyzstan","country_name":"Kyrgyzstan"},
         {"country_code":"Laos","country_name":"Laos"},
         {"country_code":"Latvia","country_name":"Latvia"},
         {"country_code":"Lebanon","country_name":"Lebanon"},
         {"country_code":"Lesotho","country_name":"Lesotho"},
         {"country_code":"Liberia","country_name":"Liberia"},
         {"country_code":"Libya","country_name":"Libya"},
         {"country_code":"Liechtenstein","country_name":"Liechtenstein"},
         {"country_code":"Lithuania","country_name":"Lithuania"},
         {"country_code":"Luxembourg","country_name":"Luxembourg"},
         {"country_code":"Macao SAR","country_name":"Macao SAR"},
         {"country_code":"Macedonia","country_name":"Macedonia"},
         {"country_code":"Madagascar","country_name":"Madagascar"},
         {"country_code":"Malawi","country_name":"Malawi"},
         {"country_code":"Malaysia","country_name":"Malaysia"},
         {"country_code":"Maldives","country_name":"Maldives"},
         {"country_code":"Mali","country_name":"Mali"},
         {"country_code":"Malta","country_name":"Malta"},
         {"country_code":"Martinique","country_name":"Martinique"},
         {"country_code":"Mauritania","country_name":"Mauritania"},
         {"country_code":"Mayotte","country_name":"Mayotte"},
         {"country_code":"Mexico","country_name":"Mexico"},
         {"country_code":"Micronesia","country_name":"Micronesia"},
         {"country_code":"Moldova","country_name":"Moldova"},
         {"country_code":"Monaco","country_name":"Monaco"},
         {"country_code":"Mongolia","country_name":"Mongolia"},
         {"country_code":"Montserrat","country_name":"Montserrat"},
         {"country_code":"Morocco","country_name":"Morocco"},
         {"country_code":"Mozambique","country_name":"Mozambique"},
         {"country_code":"Myanmar","country_name":"Myanmar"},
         {"country_code":"Namibia","country_name":"Namibia"},
         {"country_code":"Nauru","country_name":"Nauru"},
         {"country_code":"Nepal","country_name":"Nepal"},
         {"country_code":"Netherlands","country_name":"Netherlands"},
         {"country_code":"Netherlands Antilles","country_name":"Netherlands Antilles"},
         {"country_code":"New Caledonia","country_name":"New Caledonia"},
         {"country_code":"New Zealand","country_name":"New Zealand"},
         {"country_code":"Nicaragua","country_name":"Nicaragua"},
         {"country_code":"Niger","country_name":"Niger"},
         {"country_code":"Niue","country_name":"Niue"},
         {"country_code":"Norfolk Island","country_name":"Norfolk Island"},
         {"country_code":"North Korea","country_name":"North Korea"},
         {"country_code":"Norway","country_name":"Norway"},
         {"country_code":"Oman","country_name":"Oman"},
         {"country_code":"Pakistan","country_name":"Pakistan"},
         {"country_code":"Panama","country_name":"Panama"},
         {"country_code":"Papa New Guinea","country_name":"Papa New Guinea"},
         {"country_code":"Paraguay","country_name":"Paraguay"},
         {"country_code":"Peru","country_name":"Peru"},
         {"country_code":"Philippines","country_name":"Philippines"},
         {"country_code":"Pitcairn Islands","country_name":"Pitcairn Islands"},
         {"country_code":"Poland","country_name":"Poland"},
         {"country_code":"Portugal","country_name":"Portugal"},
         {"country_code":"Puerto Rico","country_name":"Puerto Rico"},
         {"country_code":"Qatar","country_name":"Qatar"},
         {"country_code":"Reunion","country_name":"Reunion"},
         {"country_code":"Romania","country_name":"Romania"},
         {"country_code":"Russia","country_name":"Russia"},
         {"country_code":"Rwanda","country_name":"Rwanda"},
         {"country_code":"Samoa","country_name":"Samoa"},
         {"country_code":"San Marino","country_name":"San Marino"},
         {"country_code":"Sao Tome and Pricipe","country_name":"Sao Tome and Pricipe"},
         {"country_code":"Saudi Arabia","country_name":"Saudi Arabia"},
         {"country_code":"Senegal","country_name":"Senegal"},
         {"country_code":"Serbia","country_name":"Serbia"},
         {"country_code":"Seychelles","country_name":"Seychelles"},
         {"country_code":"Sierra Leone","country_name":"Sierra Leone"},
         {"country_code":"Singapore","country_name":"Singapore"},
         {"country_code":"Slovakia","country_name":"Slovakia"},
         {"country_code":"Slovenia","country_name":"Slovenia"},
         {"country_code":"Solomon Islands","country_name":"Pakistan"},
         {"country_code":"Somalia","country_name":"Somalia"},
         {"country_code":"South Africa","country_name":"South Africa"},
         {"country_code":"Pakistan","country_name":"Pakistan"},
         {"country_code":"Sri Lanka","country_name":"Sri Lanka"},
         {"country_code":"St. Helena","country_name":"St. Helena"},
         {"country_code":"St. Kitts","country_name":"St. Kitts"},
         {"country_code":"St. Lucia","country_name":"St. Lucia"},
         {"country_code":"St. Pierre and Miquelon","country_name":"St. Pierre and Miquelon"},
         {"country_code":"St. Vincent","country_name":"St. Vincent"},
         {"country_code":"Sudan","country_name":"Sudan"},
         {"country_code":"Suriname","country_name":"Suriname"},
         {"country_code":"Swaziland","country_name":"Swaziland"},
         {"country_code":"Sweden","country_name":"Sweden"},
         {"country_code":"Switzerland","country_name":"Switzerland"},
         {"country_code":"Syria","country_name":"Syria"},
         {"country_code":"Taiwan","country_name":"Taiwan"},
         {"country_code":"Tajikistan","country_name":"Tajikistan"},
         {"country_code":"Tanzania","country_name":"Tanzania"},
         {"country_code":"Thailand","country_name":"Thailand"},
         {"country_code":"Togo","country_name":"Togo"},
         {"country_code":"Tokelau","country_name":"Tokelau"},
         {"country_code":"Tonga","country_name":"Tonga"},
         {"country_code":"Trinidad","country_name":"Trinidad"},
         {"country_code":"Tunisia","country_name":"Tunisia"},
         {"country_code":"Turkey","country_name":"Turkey"},
         {"country_code":"Turkmenistan","country_name":"Turkmenistan"},
         {"country_code":"Turks and Caicos Islands","country_name":"Turks and Caicos Islands"},
         {"country_code":"Tuvalu","country_name":"Tuvalu"},
         {"country_code":"Uganda","country_name":"Uganda"},
         {"country_code":"Ukraine","country_name":"Ukraine"},
         {"country_code":"UAE","country_name":"UAE"},
         {"country_code":"UK","country_name":"UK"},
         {"country_code":"Uruguay","country_name":"Uruguay"},
         {"country_code":"Uzbekistan","country_name":"Uzbekistan"},
         {"country_code":"Vanuatu","country_name":"Vanuatu"},
         {"country_code":"Venezuela","country_name":"Venezuela"},
         {"country_code":"Vietnam","country_name":"Vietnam"},
         {"country_code":"US Virgin Islands","country_name":"US Virgin Islands"},
         {"country_code":"Britis Virgin Islands","country_name":"Britis Virgin Islands"},
         {"country_code":"Wallis and Futuna","country_name":"Wallis and Futuna"},
         {"country_code":"Yemen","country_name":"Yemen"},
         {"country_code":"Yugoslavia","country_name":"Yugoslavia"},
         {"country_code":"Zambia","country_name":"Zambia"},
         {"country_code":"Zimbabwe","country_name":"Zimbabwe"},
         {"country_code":"Australia","country_name":"Australia"},
         {"country_code":"USA","country_name":"USA"},
         {"country_code":"Palestine","country_name":"Palestine"},
         {"country_code":"Benin","country_name":"Benin"},
         {"country_code":"Saint Barthelemy","country_name":"Saint Barthelemy"},
         {"country_code":"Aland Islands","country_name":"Aland Islands"},
         {"country_code":"American Samoa","country_name":"American Samoa"},
         {"country_code":"Aruba","country_name":"Aruba"},
         {"country_code":"Guernsey","country_name":"Guernsey"},
         {"country_code":"Isle of Man","country_name":"Isle of Man"},
         {"country_code":"Jersey","country_name":"Jersey"},
         {"country_code":"Marshall Islands","country_name":"Marshall Islands"},
         {"country_code":"Montenegro","country_name":"Montenegro"},
         {"country_code":"Northern Mariana Islands","country_name":"Northern Mariana Islands"},
         {"country_code":"Palau","country_name":"Palau"},
         {"country_code":"Western Sahara","country_name":"Western Sahara"}
         
         
         
         
         ];
         $scope.selectedcountry = {country_code:"UK"};
         });